sudo: reqiured
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t kadekchrisna/docker-react .

script:
  - docker run -e CI=true kadekchrisna/docker-react npm run test
