sudo: reqiured
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t kadekchrisna/docker-react .

script:
  - docker run -e CI=true kadekchrisna/docker-react npm run test

deploy:
  provider: "elasticbeanstalk"
  region: "us-east-2"
  app: "docker-react-frontend"
  env: "DockerReactFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-469244896249"
  bucker_path: "docker-react-frontend"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
